manifest:
  self:
    path: Euler  # 修正拼写错误

  remotes:
    - name: github
      url-base: ssh://git@github.com 
    - name: origin 
      url-base: ssh://git@github.com/zagerx  # 改为 SSH 协议

  defaults:
    remote: origin
    revision: master
   
  projects:
    - name: zephyr
      remote: github
      repo-path: zephyrproject-rtos/zephyr
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - hal_stm32
          - segger
          - zcbor
    - name: ProtocolV4
      path: modules/lib/ProtocolV4
      submodules: true
      revision: master

    - name: motorlib
      path: modules/lib/motorlib
      revision: master

    - name: CommonLibrary
      path: modules/lib/CommonLibrary
      revision: master

    - name: CustomMCUBoot
      path: bootloader/mcuboot
      remote: origin  # 改为存在的 remote
      revision: CustomMCUBoot

    - name: syrius-dts
      path: syrius-dts/
      remote: origin  # 改为存在的 remote
      revision: master
    
    - name: syrius-boards
      path: syrius-boards/
      remote: origin  # 改为存在的 remote
      revision: master

    # 添加 canopennode 项目（关键修改）
    - name: canopennode
      remote: github
      repo-path: zephyrproject-rtos/canopennode
      revision: master  # 推荐使用兼容 v4.1.0 的版本
      path: modules/lib/canopennode  # 统一放在 modules/lib 目录 